Webauthn Authentication Module
OpenIdentityPlatform/OpenAM pull request #160
Opened 2019-07-12 06:59 UTC by maximthomas

2019-07-12 11:42 UTC, vharseko requested changes

2019-07-12 11:42 UTC, vharseko commented on openam-authentication/openam-auth-webauthn/src/main/resources/amAuthWebAuthn.properties
> +org.openidentityplatform.openam.authentication.modules.webauthn.WebAuthnAuthentication.authlevel=Auth Level
duplicate authlevel

2019-07-12 11:42 UTC, vharseko commented on openam-authentication/openam-auth-webauthn/src/main/resources/amAuthWebAuthn.properties
> +org.openidentityplatform.openam.authentication.modules.webauthn.WebAuthnAuthentication.description=WebAuthn Authentication
duplicate descriptions

2019-07-12 11:42 UTC, vharseko commented on openam-authentication/openam-auth-webauthn/src/main/resources/amAuthWebAuthn.properties
> +org.openidentityplatform.openam.authentication.modules.webauthn.WebAuthnAuthentication.userAttribute=User attribute to retrieve Public Keys
duplicate

2019-07-12 11:42 UTC, vharseko commented on openam-authentication/openam-auth-webauthn/src/main/java/org/openidentityplatform/openam/authentication/modules/webauthn/WebAuthnAuthentication.java
> +		return ISAuthConstants.LOGIN_SUCCEED;
don't setAuthLevel

2019-07-12 12:50 UTC, maximthomas commented
@vharseko see bd469f4

2019-07-12 13:10 UTC, maximthomas commented
Added local development notes: 8e58d69 e2937f1

2019-07-15 08:36 UTC, vharseko commented on openam-authentication/openam-auth-webauthn/README.md
> +|**Auth Level**| Modlue Authentication Level|
Module ?

2019-07-15 08:49 UTC, maximthomas commented on openam-authentication/openam-auth-webauthn/README.md
> +|**Auth Level**| Modlue Authentication Level|
Headings at 13 line and 29 line

2019-07-15 08:58 UTC, merged